const USERS_COUNT = 'USERS_COUNT';
const NEW_MESSAGE = 'NEW_MESSAGE';
const ADD_MESSAGE = 'ADD_MESSAGE';
const SET_NAME = 'SET_NAME';
const USER_DISCONNECTED = 'USER_DISCONNECTED';
const NEW_USER_CONNECTED = 'NEW_USER_CONNECTED';
const CONNECTED = 'CONNECTED';

module.exports = {
    USERS_COUNT,
    NEW_MESSAGE,
    ADD_MESSAGE,
    SET_NAME,
    USER_DISCONNECTED,
    NEW_USER_CONNECTED,
    CONNECTED,
};
